# Generated by Django 4.0.2 on 2022-02-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_user_phone'),
        ('dashboard', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.shippingaddress'),
        ),
    ]
