# Generated by Django 4.0.2 on 2022-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_order_approve_status_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_ordered',)},
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_status',
            field=models.BooleanField(default=False),
        ),
    ]
