# Generated by Django 4.0.2 on 2022-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_order_options_order_shipped_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_status',
            field=models.BooleanField(default=False),
        ),
    ]
