# Generated by Django 4.0.2 on 2022-02-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_order_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
