# Generated by Django 4.0.2 on 2022-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_coupon_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('new', 'NEW'), ('ref', 'REF')], max_length=10, null=True),
        ),
    ]
