# Generated by Django 4.0.2 on 2022-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_category_category_discount_product_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_now',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
