# Generated by Django 4.0.2 on 2022-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
