# Generated by Django 4.0.2 on 2022-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100, null=True)),
                ('banner_image', models.ImageField(default='images/slider.svg', null=True, upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
