# Generated by Django 4.0.2 on 2022-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_name',
            new_name='banner_description',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
