# Generated by Django 4.0.2 on 2022-03-16 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
