# Generated by Django 4.0.2 on 2022-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
