# Generated by Django 4.0.2 on 2022-03-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
