# Generated by Django 4.0.2 on 2022-03-21 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_order_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
