# Generated by Django 4.0.2 on 2022-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biopic',
            field=models.ImageField(default='fitness/images/avater.svg', null=True, upload_to='images'),
        ),
    ]
