# Generated by Django 4.0.2 on 2022-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_user_biopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biopic',
            field=models.ImageField(default='images/avater.svg', null=True, upload_to='images'),
        ),
    ]
