# Generated by Django 4.0.2 on 2022-02-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_user_biopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biopic',
        ),
    ]
